project:
  type: website

title: "Making Data Science Count Research Group"

website:
  navbar:
    title: "Making Data Science Count Research Group"
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "People"
        href: people.qmd
  site-url: https://makingdatasciencecount.com  # This stays in website:

cname: makingdatasciencecount.com  # This goes at the top level (outside website:)

format:
  html:
    theme:
      light: litera
